SuperHero.PL/Controllers/Admin/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SuperHero.BL.DomainModelVM;
using SuperHero.BL.Seeds;
using SuperHero.DAL.Entities;

namespace SuperHero.PL.Controllers.Admin
{
    
    public class RolesController : Controller
    {
        #region prop

        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<Person> userManager;
        private readonly IBaseRepsoratory<Person> person;
        #endregion

        #region Ctor
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<Person> userManager, IBaseRepsoratory<Person> person)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.person = person;
        }
        #endregion

        #region GetAll Roles
        public IActionResult GetAll()
        {
            var data = roleManager.Roles;
            return View(data);
        }

        #endregion

        #region Create Roles
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {

            var result = await roleManager.CreateAsync(model);

            if (result.Succeeded)
            {
                return RedirectToAction("GetAll");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }

            return View();
        }

        #endregion

        #region Update Roles
        public async Task<IActionResult> Update(string id)
        {
            var data = await roleManager.FindByIdAsync(id);
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Update(IdentityRole model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var result = await roleManager.UpdateAsync(model);
                    return RedirectToAction("GetAll");
                }
                else
                {
                    TempData["Message"] = null;
                    return View("Form", model);
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            TempData["Message"] = null;
            return View(model);

        }



        #endregion

        #region Delete Roles
        public async Task<IActionResult> Delete(string id)
        {
            var data = await roleManager.FindByIdAsync(id);
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(IdentityRole model)
        {

            var data = await roleManager.FindByIdAsync(model.Id);

            if (data != null)
            {
                var result = await roleManager.DeleteAsync(data);


                if (result.Succeeded)
                {
                    return RedirectToAction("GetAll");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }

            return View(model);
        }


        #endregion

        #region Add and Remover Person Group
        public async Task<IActionResult> AddOrRemoveUsers(string RoleId)
        {

            ViewBag.roleId = RoleId;

            var role = await roleManager.FindByIdAsync(RoleId);

            var model = new List<UserInRoleVM>();

            foreach (var user in await person.GetAll())
            {
                var userInRole = new UserInRoleVM()
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;
                }
                else
                {
                    userInRole.IsSelected = false;
                }

                model.Add(userInRole);
            }

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(List<UserInRoleVM> model, string RoleId)
        {

            var role = await roleManager.FindByIdAsync(RoleId);

            for (int i = 0; i < model.Count; i++)
            {

                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {

                    result = await userManager.AddToRoleAsync(user, role.Name);

                }
                else if (!model[i].IsSelected && (await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

            }

            return RedirectToAction("GetAll");
        }
        #endregion


    }
}

SuperHero.PL/Controllers/Admin/Social/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using SuperHero.BL.Interface;

namespace SuperHero.PL.Controllers.Admin.Social
{
    public class GroupController : Controller
    {
        #region Pop
        private readonly IBaseRepsoratory<Group> groups;
        private readonly IMapper mapper;
        private readonly IBaseRepsoratory<Person> person;
        private readonly IBaseRepsoratory<PersonGroup> personGroup;
        private readonly IServiesRep servis;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<Person> userManager;
        #endregion

        #region Ctor
        public GroupController(IBaseRepsoratory<Group> groups, IMapper mapper, IBaseRepsoratory<Person> person, IBaseRepsoratory<PersonGroup> personGroup, IServiesRep servis, RoleManager<IdentityRole> roleManager, UserManager<Person> userManager)
        {
            this.groups = groups;
            this.mapper = mapper;
            this.person = person;
            this.personGroup = personGroup;
            this.servis = servis;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        #endregion

        #region GetAll Groups
        public async Task<IActionResult> GetAll()
        {
            var data = await groups.GetAll();
            var result = mapper.Map<IEnumerable<GroupVM>>(data);
            return View(result);
        }

        #endregion

        #region Create Groups
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.ID = null;
            TempData["Message"] = null;
            return PartialView("Form");
        }
        public async Task<IActionResult> Create(GroupVM groupVM)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var result = mapper.Map<Group>(groupVM);
                    result.CreatedTime = DateTime.Now.Date;
                    await groups.Create(result);

                    TempData["Message"] = "saved Successfuly";
                    return RedirectToAction("GetAll");
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }

            //ModelState.Clear();
            TempData["Message"] = null;


            ViewBag.ID = null;
            return PartialView("Form", groupVM);
        }
        #endregion

        #region Edite Groups
        [HttpGet]
        public async Task<IActionResult> Edite(int id)
        {
            var data = await groups.GetByID(id);
            var result = mapper.Map<GroupVM>(data);
            TempData["Message"] = null;
            return PartialView("Form", result);
        }
        public async Task<IActionResult> Edite(GroupVM groupVM)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    groupVM.CreatedTime = DateTime.Now;
                    var result = mapper.Map<Group>(groupVM);
                    await groups.Update(result);
                    TempData["Message"] = "saved Successfuly";
                    return RedirectToAction("GetAll");
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }

            //ModelState.Clear();
            TempData["Message"] = null;

            ViewBag.ID = "Edite";
            return View("Form", groupVM);
        }
        #endregion

        #region Delete Groups

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var data = await groups.GetByID(id);
            var result = mapper.Map<GroupVM>(data);
            TempData["Message"] = null;
            return PartialView("Delete", result);
        }


        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(GroupVM obj)
        {


            try
            {
                if (ModelState.IsValid)
                {   
                    var result = mapper.Map<Group>(obj);
                    await servis.DeletePersonGroup(result.ID);
                    await groups.Delete(result.ID);
                    return RedirectToAction("GetAll");
                }

            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            return PartialView("Delete", obj);

        }
        #endregion

        #region AddOrRemoveGroups
        public async Task<IActionResult> AddOrRemoveGroups(int id)
        {

            ViewBag.Id = id; 

            var DataGroup = await groups.GetByID(id);

            var model = new List<GroupInRoleVM>();

            foreach (var use in await person.GetAll())
            {
                var groupInRole = new GroupInRoleVM()
                {
                    Id = use.Id,
                    Name = use.UserName,
                    FullName =use.FullName,
                    Image = use.Image,
                    gender = use.gender
                };

                if (await servis.GetAll(id, use.Id))
                {
                    groupInRole.IsSelected = true;
                }
                else
                {
                    groupInRole.IsSelected = false;
                }

                model.Add(groupInRole);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveGroups(List<GroupInRoleVM> model, int id)
        {

            var group = await groups.GetByID(id);

            for (int i = 0; i < model.Count; i++)
            {

                var user = await userManager.FindByIdAsync(model[i].Id);
                if(user != null)
                {
                    if (model[i].IsSelected && !await servis.GetAll(group.ID, user.Id))
                    {
                        var result = new PersonGroup()
                        {
                            PersonId = user.Id,
                            Group = group.ID

                        };

                        await personGroup.Create(result);

                    }
                    else if (!model[i].IsSelected && await servis.GetAll(group.ID, user.Id))
                    {
                        var result = await servis.FindById(user.Id, group.ID);

                        await personGroup.Delete(result.ID);
                    }
                }
                else
                {
                    continue;
                }

            }

            return RedirectToAction("GetAll");
        }
        #endregion
    }
}

SuperHero.PL/Views/Group/AddOrRemoveGroups.cshtml
@model List<GroupInRoleVM>

@{
    ViewData["Title"] = "AddOrRemoveGroups";
    var RoleId = ViewBag.Id;
    Layout = "~/Views/AdminLayout/_Layout.cshtml";
}

<h1></h1>


<form method="post" class="form-group">
    <div class="row">
        <div class="col-sm-8"></div>
        <div class="col-sm-4">
            <input type="submit" style="text-align:center" value="  Add Person" class=" btn1 third  w-75" />
        </div>


    </div>
    <br />
    <br />
    <table id="example" class="table" style="width:100%;color:darkgrey">
        <thead>
            <tr>
                <th></th>
                <th>Full Name</th>

                <th>User Name</th>

                <th></th>
            </tr>
        </thead>
        <tbody>


            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
            <td>
                    @if (@Model[i].Image == null)
                    {
                        if (@Model[i].gender == 0)
                        {
                        <div class="Image" style="background-image:url('/files/imgs/men.jpg') ; width:50px ; height:50px ; border-radius : 50%;background-size:cover;margin:auto; background-position:center; background-repeat:no-repeat ;">
                        </div>

                        }
                        else
                        {
                        <div class="Image" style="background-image:url('/files/imgs/young-woman-avatar-cartoon-character-profile-picture-young-woman-wearing-blue-t-shirt-avatar-cartoon-character-vector-149732076.jpg') ; width:50px;margin:auto ; height:50px ; border-radius : 50%;background-size:cover; background-position:center; background-repeat:no-repeat ;">
                        </div>

                        }
                    }
                    else
                    {
                    <div class="Image" style="background-image:url('/files/imgs/@Model[i].Image') ; width:50px ; height:50px ; border-radius : 50%;background-size:cover;margin:auto; background-position:center; background-repeat:no-repeat ;">
                    </div>
                    }


            </td>
            <td>
                    @Model[i].FullName
            </td>
            <td>
                <label asp-for="@Model[i].IsSelected">@Model[i].Name</label>
            </td>
            <td>
                <input asp-for="@Model[i].IsSelected" type="checkbox" class="filled-in">


                <input type="hidden" asp-for="@Model[i].Id" />
                <input type="hidden" asp-for="@Model[i].Name" />
            </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <br />
   


</form>

<a asp-controller="Roles" asp-action="Edit" asp-route-id="@RoleId">Cancle</a>

@section CSS{
    <partial name="~/views/person/Partial/css.cshtml" />
    <style>
        div.dataTables_wrapper div.dataTables_filter input {
            width:75%;
            margin-right:30px
            
        }
    </style>
}
    @section JqueryValidation{
    <partial name="~/views/person/Partial/Script.cshtml" />
}

SuperHero.PL/Views/Group/Delete.cshtml
@model GroupVM

<div class="card shadow-sm">

    <div class="card-header">
        <h3 class="card-title">Delete Group</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-md-7">
                <a>@TempData["error"]</a>
                <div asp-validation-summary="All"></div>
                <form method="post" asp-controller="Group" enctype="multipart/form-data">

                    <div class="mb-5">
                        <div class="form-floating mb-2">
                            <input type="text" class="form-control" disabled  placeholder="Name" asp-for="Name" />
                            <label asp-for="Name"></label>
                        </div>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                   
                    
                        <center>
                            <button type="submit" class="btn btn-danger" >
                                <i class="uil uil-exclamation-octagon"></i>  Delete
                            </button>

                           
                        </center>
                   

                </form>
            </div>
        </div>
    </div>
</div>

@section CSS{
    <partial name="~/views/person/Partial/css.cshtml" />

}
    @section JqueryValidation{
    <partial name="~/views/person/Partial/Script.cshtml" />
}

SuperHero.PL/Views/Group/Form.cshtml
@model GroupVM



<div class="card shadow-sm">

    <div class="card-header">
        <h3 class="card-title">@(ViewBag.Delete == "Delete" ? "Delete" : (ViewBag.ID != null ? "Edit" : "Add")) Group</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <a>@TempData["error"]</a>
                <div asp-validation-summary="All"></div>
                <form method="post" asp-controller="Group" enctype="multipart/form-data">

                    <div class="mb-5">
                        <div class="form-floating mb-2">
                            <input type="text" class="form-control" placeholder="Name" asp-for="Name" />
                            <label asp-for="Name"></label>
                        </div>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

              

                  
                        <center>
                            <button type="submit" class="btn btn-primary">
                                <i class="uil uil-check"></i>Save
                            </button>

                            <a asp-action="GetAll" asp-controller="Group" class="btn btn-danger">return</a>
                        </center>
                   


                </form>
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>
</div>

@section CSS{
    <partial name="~/views/person/Partial/css.cshtml" />

}
    @section JqueryValidation{
    <partial name="~/views/person/Partial/Script.cshtml" />
}

SuperHero.PL/Views/Group/GetAll.cshtml
@model IEnumerable<GroupVM>

    @{
        ViewData["Title"] = "GetAll";
        Layout = "~/Views/AdminLayout/_Layout.cshtml";
    }

    @section CSS{
        <partial name="~/views/person/Partial/css.cshtml" />
    }

    <a class="btn1 third col-sm-3  me-2 js-friends" data-url="/Group/Create" href="javascript:;"> &nbsp; &nbsp; &nbsp;<i class="uil uil-create-dashboard "></i> &nbsp; Create</a>

    
    <br />
    <br />
    <table id="example" class="table" style="width:100%;color:darkgrey">
        <thead>
            <tr>

                <th>Name</th>

                <th>createdTime</th>

                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>@item.Name</td>

                    <td>@item.CreatedTime</td>

                    <td>
                        <div class="dropdown show">
                            <p class="btn btn-outline-info" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Action
                            </p>

                            <div class="dropdown-menu align-items-center " aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item ancor btn btn-primary  js-friends" href="javascript:;" data-url="/Group/Edite/@item.ID" data-update="true">

                                    Edite
                                </a>
                            <a style="text-align: center" class="dropdown-item  js-friends" href="javascript:;" data-url="/Group/Delete/@item.ID" data-update="true">

                                    Delete
                                </a>
                                <a style="text-align: center" class="dropdown-item" asp-action="AddOrRemoveGroups" asp-controller="Group" asp-route-id="@item.ID">

                                    Add Person
                                </a>

                            </div>
                        </div>
                    </td>
                </tr>
            }


        </tbody>

    </table>


<partial name="~/views/post/Model.cshtml">
    @section JS{
        <partial name="~/views/post/scripts.cshtml">

            <partial name="~/views/person/Partial/script.cshtml" />
            <script src="~/dashboard/lib/bootbox.js/bootbox.min.js"></script>

        }