SuperHero.PL/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace SuperHero.PL.Controllers
{
    public class LanguageController : Controller
    {
        [HttpGet]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

    }
}

SuperHero.PL/Views/FirstPage/_BodyFirstBage.cshtml
<div class="content">
    <div class="left">
        <h1><span>Super H</span>eros</h1>

        <p>@SharedLocalizer["AimoftheWeb"]</p>
        <div id="btn_play">
            <a style=" text-decoration:none;" href="#"><i class="fa fa-play" aria-hidden="true"></i></a>
        </div>
        <div class="btn" id="btn_play">
            <a style=" text-decoration:none;" href=""> @SharedLocalizer["Discover"]</a>
        </div>
    </div>
    <div class="right">
        <div class="box">
            <img class="book" alt="world down" src="~/firstpage/image/world down syndrome day-amico.svg" />
        </div>
    </div>
</div>

SuperHero.PL/Views/FirstPage/_FirstPageLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link href="~/firstpage/css/main.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Oswald:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />
    <link href="~/firstpage/image/flash.svg" rel="icon">
    <style>
        a:hover{
            text-decoration:none;
            cursor: pointer;
        }
    </style>
    @RenderSection("CSSLogin",required:false)
</head>
<body>
   
    <section id="home">

        <partial name="~/views/firstpage/_headerfirstpage.cshtml">
        <partial name="~/views/firstpage/_BodyFirstBage.cshtml">
    </section>
    @RenderBody()
    @RenderSection("JqueryValidation",required:false)
    <!-- scripts -->
    @RenderSection("ScriptsLogin",required:false)
@*    <script src="~/jquery-validation/additional-methods.js"></script>*@
    <script src="~/jquery-validation/jquery.validate.js"></script>
    <script src="~/jquery-validation/validation-styling.js"></script>

    <script src="~/firstpage/js/main.js"></script>
</body>
</html>

SuperHero.PL/Views/FirstPage/_HeaderFirstPage.cshtml
@{
    var Culture = System.Threading.Thread.CurrentThread.CurrentCulture.Name;
}
@if (Culture == "ar-EG")
{
    <link href="~/Ar.css" rel="stylesheet" />
}
else
{
    <link href="~/En.css" rel="stylesheet" />
}
<header>
    <div id="logo">
        <a style=" text-decoration:none;" href="#">
            <span id="span1">Super</span><span id="span2">Heros</span>
        </a>
    </div>
    <nav id="navbar">
        <div id="quit">
            <i class="fa fa-times" aria-hidden="true" onclick="toggle()"></i>
        </div>
        <ul>
            <li><a style=" text-decoration:none;" href="#"> @SharedLocalizer["Home"]</a></li>
            <li><a style=" text-decoration:none;" href="#"> @SharedLocalizer["Problem"]</a></li>
            <li><a style=" text-decoration:none;" href="#"> @SharedLocalizer["about"]</a></li>
            <li><a style=" text-decoration:none;" href="#"> @SharedLocalizer["contact"]</a></li>
            <li>
                <div class="dropdown">
                    <i style="font-size:30px;color:#1EB2A6;cursor:pointer" class="fa-solid fa-language"></i>
                   @* <i class="fa-solid fa-list dropbtn" onclick="myFunction()"></i>*@
                    <div style="text-align:center" id="myDropdown" class="dropdown-content">

                        @if (Culture == "ar-EG")
                        {
                            
                                <a class="dropdown-item d-flex justify-content-between"
                                   href="@Url.Action("SetLanguage", "Language", new {
                                                                          culture = "en-US",
                                                                          returnUrl = Context.Request.Path + Context.Request.QueryString
                                                                      })">

                                 @SharedLocalizer["English"]
                                </a>
                            
                                    }
                        else
                        {
                            
                                <a class="dropdown-item d-flex justify-content-between"
                                   href="@Url.Action("SetLanguage", "Language", new {
                                                                          culture = "ar-EG",
                                                                          returnUrl = Context.Request.Path + Context.Request.QueryString
                                                                      })">

                                    @SharedLocalizer["Arabic"]
                                </a>
                            
                        }
                            @*<a style=""><i class="fa-solid fa-spell-check"></i>Arabic</a>
                            <a ><i class="fa-solid fa-trash-can"></i> English</a>
                       *@
                    </div>
                </div>
            </li>

            <li><a style=" text-decoration:none;" class="Register" data-toggle="modal" data-target="#exampleModal" style="text-decoration:none"> @SharedLocalizer["Login"]</a></li>

        </ul>
    </nav>
    <div id="bars" onclick="toggle()">
        <div class="bar b"></div>
        <div class="bar"></div>
        <div class="bar b"></div>
    </div>
</header>